HOSTS:
  debian-82-x64:
    roles:
      - master
    platform: debian-8-amd64
    box: puppetlabs/debian-8.2-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/debian-8.2-64-nocm
    hypervisor: vagrant
    # Needs to be AIO, otherwise hieradatadir isn't read
    type: aio
    # Needs to be explecitly set
    hieradatadir: /etc/puppetlabs/code/environments/production/hieradata

CONFIG:
  #log_level: verbose
  forward_ssh_agent: true
  vagrant_memsize: 1024
  vagrant_cpus: 1
